### ISSUE TITLE
Trying to understand how to add a session id 

### ISSUE THREAD

**Issue by talkingtab** [simov/purest#12]
I am using the  "grant" module and now that I have an access token from Facebook I want to get the user information. In order to do correlate this information I want to add a session id to my Purest call to facebook for "/me" but can't understand how. 

The grant package is GREAT!

**Comment by simov** [comment]
Try this:

```js
var facebook = new Purest({provider:'facebook'})
facebook.query()
  .get('me')
  .qs({session_id:'...'})
  .auth('[access token]')
  .request(function (err, res, body) {
  })
```
