### ISSUE TITLE
switch in query

### ISSUE THREAD

**Issue by kvslee** [simov/purest#13]
I wonder how I can write switch statements in query. I want to query depending on a search index (either id or name) For example,
From 
```javascript
provider.query()
.get('patrons')
.qs({id: 111, name: "Ronda"})
})
```
To, Something like this:
```javascript
provider.query()
.get('patrons')
.qs(function() {
         switch (queryIndex) {
               case "id": 
                 return {id, query}; 
               case "name":
                 return {name, query}; 
         }
  })
```

**Comment by simov** [comment]
That depends on your application logic. You just have to set the parameter, it's not like queueing a real database. That's REST. Give me the bigger picture.

**Comment by kvslee** [comment]
You are right. I was kind in a mixed bag of querying DB and REST. I have REST API api/patrons that returns patron lists in a following format. I want to  apply a query parameter depending on the user choice of query index option (either id or name, not both). I find a problem that the API does not provide the 'names' property as a query parameter. Is there any reasonable way to work around this? It seems that I have no option but fetching all data and filter with a name afterward. It looks a bad choice for performance.   

```json
{
  "total": 1,
  "entries": [
    {
      "id": 1000001,
      "names": [
        "Robert Lee"
      ],
      "emails": [
        "cool@gmail.com"
      ]
    }
  ]
}
```
```javascript
var findPatrons = function(req, res, next) {
 
  var queryPatron = req.query.patron;  // query patron
  var queryIndex = req.query.index;  //query index

  switch (queryIndex) {
    case "recordNum": 
        return sierraApi.query()
         .get('patrons')
         .qs({
              id : queryPatron,
          })   
          .request(function (err, _res, body) {
              res.setHeader('content-type', 'application/json')
              if (err || _res.statusCode !== 200) { console.log(err) }
               res.end(JSON.stringify(body.entries))
          })

    case "patronName":
        return sierraApi.query()
         .get('patrons')
         .qs({
              names : queryPatron,
          })   
          .request(function (err, _res, body) {
              res.setHeader('content-type', 'application/json')
              if (err || _res.statusCode !== 200) { console.log(err) }
               res.end(JSON.stringify(body.entries))
          })           
  }
};
```
The parameter 'id' works fine. But the parameter 'names' is not.

**Comment by simov** [comment]
> I find a problem that the API does not provide the 'names' property as a query parameter.

If the API provider doesn't provide that option, there is nothing you can do about it really :)

Generally speaking making a query by id will be faster for both of you. The database engine will make the query faster, you'll get the results faster, and then you just have to filter them up. Searching by item in array is generally not fast for a database. The real problem for you and your users would be if you know only the name upfront.

**Comment by kvslee** [comment]
Thanks Simov.  It was a good topic to think about.  I will close this issue.  Thanks you again for the great library.
