### ISSUE TITLE
Allow passing custom HTTP Agent

### ISSUE THREAD

**Issue by bitinn** [simov/purest#14]
This enables passing custom agent when you can, say, proxy a request, or accept self-signed certificate.

The proxy options is especially useful to me because here in China, many website do require a bit of network tunneling to work...

I did try to make it happen on Node.js core, but I guess that's probably too large a change to push forward, allowing custom agent passing on userland code seems like the best solution to me.

Alternative, which require more efforts, would be to allow user to take over the `request` module, eg. can I implement the same interface using `node-fetch` instead of `request`?

But really as long as I can make a request to Twitter using my local tunnel, I am a happy man.

ref:
- https://github.com/nodejs/node/issues/1490
- https://github.com/bitinn/node-fetch#options

**Comment by simov** [comment]
Request accepts a custom agent through its `agent` option, so as long as you are using the [Basic API](https://github.com/simov/purest#basic-api) you can pass that option to the underlying request module.

Let me know if that works for you.

**Comment by bitinn** [comment]
OK that's good to know.

By the way, is it possible to do this?

```
		client.query()
			.get('account/verify_credentials', REQUEST_OPTIONS)
			.auth(opts.access_token, opts.access_secret)
			.request(function(err, res, body) {
			...
```

**Comment by simov** [comment]
Oh, you can actually use the `options` method:

```js
client.query()
            .get('account/verify_credentials')
            .auth(opts.access_token, opts.access_secret)
            .options(REQUEST_OPTIONS)
            .request(function(err, res, body) {
            ...
```

Totally forgot about that.

As for this question:

> Can I implement the same interface using node-fetch instead of request?

I'm working on a rewrite where the Purest's logic is extracted into modules that consume a common interface, so as long as you write a thin wrapper for your HTTP client of choice exposing the same interface, Purest will be able to use it.

**Comment by bitinn** [comment]
Cool, and didn't know you were already working on the abstraction!

**Comment by simov** [comment]
Yes, it will be a major release because I'll probably break a few things, for the benefit of having more flexible solution :)
