### ISSUE TITLE
Oauth 1.0 Signature (Yahoo)

### ISSUE THREAD

**Issue by keithkelly** [simov/purest#15]
I have been having an issue when I attempt to refresh the Yahoo Oauth tokens.  Every time I attempt to refresh I am getting a oauth_problem=signature_invalid error.

According to the Yahoo documentation the token should be a concatenated string of the consumer secret and token secret separated by an "&" character.  When I debug the request I am seeing a short string of characters that I am not sure how they were generated.

How is that signature being generated? Should that be replaced with the concatenated consumer and token secrets?

**Comment by simov** [comment]
I guess you are using [this example](https://github.com/simov/purest#consumer-requests-to-update-access-token---oauth10), right? The first 4 parameters are pretty self explanatory, the `session_handle` parameter is like the `refresh_token` in OAuth2. You receive that parameter at the end of the OAuth flow when authenticating, so you need to store it somewhere for a later use.

**Comment by keithkelly** [comment]
I am using that example.  I am storing the session_handle and using it in the request as well.

**Comment by simov** [comment]
It works on my end, just checked. Paste your code here to reproduce the error. My best bet is that you are doing something wrong :)

**Comment by keithkelly** [comment]
Me doing something wrong would be a pretty good bet. :)

I am using Firebase to store the tokens.  The tokens were stored when the app was authorized.

Here is the code I am using.  I am using placeholders for the sensitive data and removed the code that sends me an email when the request fails.

```
var Firebase 	= require('firebase'),
  firebase		= new Firebase( [My Firebase app] ),
  Purest    	= require('purest'),
  yahoo     	= new Purest({ provider: 'yahoo', debug: true });

firebase.child('auth/yahoo').once('value', function(tokens) {
  // Refresh yahoo token
  yahoo.query('oauth').update('token').oauth({
    consumer_key:     [My consumer key],
    consumer_secret:  [My consumer secret],
    token:            tokens.val().oauth_token,
    token_secret:     tokens.val().oauth_token_secret,
    session_handle:   tokens.val().oauth_session_handle
  }).request(function(error, res, body) {
    if(res.statusCode === 200) {
      // Parse tokens
      var tokens = {}, 
        token  = body.split('&');
      for(var i = 0; i < token.length; i++) {
        var key   = token[i].substr(0, token[i].indexOf('=')),
            value = token[i].substr(token[i].indexOf('=') + 1);
        tokens[key] = value;
      }

      // Store tokens in Firebase
      firebase.child('auth/yahoo').set(tokens);
    } else {
      // Send email about error
    }
  });
});
```

**Comment by simov** [comment]
Your *token parsing* logic looks a bit weird. Use a querystring parsing module instead:

```js
var qs = require('qs') // more features
// or
var qs = require('querystring') // from node core
// either way
qs.parse('body') // like JSON.parse(body), the result is a parsed object
```

After that revoke the access of your app and execute the authorization flow again, because your credentials are most probably corrupted at this point.

You can use [this app](https://grant-oauth.herokuapp.com/#/yahoo) for getting test credentials. I hope you are using [Grant](https://github.com/simov/grant) for authorization BTW :)

**Comment by keithkelly** [comment]
I think that I have found the problem.  The Oauth token contains a % symbol, but when the request is being made it is url encoding it as %25.

The token is stored as a string and I confirmed that it is being returned properly before I attempt to use it in the request.  Just in case I converted the token to a string and console logged it to check.  It was correct, but the request header is still replacing it with the url encoded version.

**Comment by simov** [comment]
> The Oauth token contains a % symbol, but when the request is being made it is url encoding it as %25.

You sure you are not dealing with corrupted token from your previous attempts? Encoding `%` to `%25` is a standard procedure. You can [test it](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) in your console.

**Comment by keithkelly** [comment]
It was definitely my fault.  The issue was how I was parsing the tokens.  I took your recommendation to use the query string parsers in the previous comments and everything works perfectly now.

Trying to learn all of this on my own in my spare time tends to lead to a lot of headaches and hacky code, lol.  Thanks for the help and advice, I really appreciate it.
