### ISSUE TITLE
purest and oAuth

### ISSUE THREAD

**Issue by Pitchlab** [simov/purest#17]
Hi Simov, 

I tried to get my api to work with the 3.0 version of purest and spent quite a bit of time but I can't get it back to work. Do you have perhaps a code snippet that shows how to use oAuth with the new setup? Many thanks!

**Comment by simov** [comment]
Can you post your code snippet where you try to make request with Purest?

**Comment by Pitchlab** [comment]
This is what I used (based on the old + the new) I also worked with adding the consumer_key in (since it seems to be missing) and removing the access secret. In the end I made a CURL request using the twitter dev tool (https://dev.twitter.com/oauth/tools/signature-generator/) and that worked, while the call from the code (when having same header params) gives a 403 authorization required result. The old purest (2.0.1) works fine with the same keys. Very strange, but maybe I'm just doing something stupid. 

```
var request = require('request')
var promise = require('bluebird')
var purest = require('purest')({request, promise})
var config = require('@purest/providers')
var twitter = purest({provider: 'twitter', config})

// alt attempt
// var twitter = purest({provider: 'twitter', key: this.apikey, secret: this.apisecret, config})

var req = twitter.query()
  .get("users/show")  
  .qs({user_id: this.userId})
  .auth(this.accessToken, this.accessSecret)
  .request()

req
  .catch((err) => {})
  .then((result) => {})
```

Thanks for having a look!

**Comment by simov** [comment]
This is how it works:

```js
var request = require('request')
var promise = require('bluebird')
var purest = require('purest')({request, promise})
var config = require('@purest/providers')
var twitter = purest({provider: 'twitter', config, key: '[CONSUMER_KEY]', secret: '[CONSUMER_SECRET]'})

var req = twitter
  .get('users/show')
  .qs({user_id: '[USER_ID]'})
  // or
  // .qs({screen_name: '[SCREEN_NAME]'})
  .auth('[ACCESS_TOKEN]', '[ACCESS_SECRET]')
  .request()

req
  .catch((err) => {
    console.log(err)
  })
  .then((result) => {
    console.log(result[1])
  })
```

You definitely have to specify your OAuth application's key and secret, that's how OAuth1.0 works.

**Comment by Pitchlab** [comment]
Thank you

**Comment by simov** [comment]
No problem. For the most part version 3.0 works in exactly the same way as 2.0, though there are [a bunch of small things changed](https://github.com/simov/purest/blob/master/CHANGELOG.md#v300-20160717).
