### ISSUE TITLE
Facebook's appsecret_proof

### ISSUE THREAD

**Issue by Kunepro** [simov/purest#21]
Hi,

I can't find the method to send Facebook the appsecret_proof that they want:
get: [Function],
  loot: [Function],
  post: [Function],
  put: [Function],
  patch: [Function],
  head: [Function],
  trace: [Function],
  options: [Function],
  delete: [Function],
  method: [Function],
  url: [Function],
  uri: [Function],
  qs: [Function],
  where: [Function],
  form: [Function],
  json: [Function],
  body: [Function],
  multipart: [Function],
  auth: [Function],
  gzip: [Function],
  encoding: [Function],
  parse: [Function],
  stringify: [Function],
  proxy: [Function],
  tunnel: [Function],
  headers: [Function],
  cookie: [Function],
  length: [Function],
  callback: [Function],
  redirect: [Function],
  timeout: [Function],
  har: [Function],
  end: [Function],
  request: [Function],
  submit: [Function],
  alias: [Function],
  query: [Function],
  api: [Function],
  token: [Function],
  oauth: [Function]

None of the methods on the Facebook provider seems to be the one I'm looking for…

**Comment by simov** [comment]
You have to send it with the request body. So depending on what request your are making it should be set in either the `qs`, `form`, `json` or `multipart` option.

**Comment by Kunepro** [comment]
Thank you.
I guess it's on me then, that's my code anyway, I tried `qs`, `form`, `json` and `multipart` , but I did not manage to get it to work yet.

```
app.get('/handle_facebook_callback', function (req, res) {
	console.log(req.query)
	console.log("handling facebook callback")
	res.end(JSON.stringify(req.query, null, 2))
	var proof = sha256(secrets.facebook.secret, req.query.access_token)
	facebook
		.get('me')
		.json({appsecret_proof: proof})
		.auth(req.query.access_token)
		.submit((err, res, body) => {console.log(body)})
});
```

This is my error:
```
{ error: 
   { message: 'API calls from the server require an appsecret_proof argument',
     type: 'GraphMethodException',
     code: 100,
     fbtrace_id: 'Ft2LvarJ/Jb' } }
```

**Comment by simov** [comment]
`GET` request does not have a body, so you should set using the `qs` method:

```js
.qs({appsecret_proof: proof})
```

**Comment by Kunepro** [comment]
I also had to fix the key, but this way it worked for me:

```
var jsSHA = require("jssha");

app.get('/handle_facebook_callback', function (req, res) {
	console.log(req.query);
	console.log("handling facebook callback");
	res.end(JSON.stringify(req.query, null, 2));

	var shaObj = new jsSHA("SHA-256", "TEXT");
	shaObj.setHMACKey(secrets.facebook.secret, "TEXT");
	shaObj.update(req.query.access_token);
	var proof = shaObj.getHMAC("HEX");

	facebook
		.get('me')
		.qs({appsecret_proof: proof})
		.auth(req.query.access_token)
		.submit((err, res, body) => {console.log(body)});
});

Many thanks!
```
