### ISSUE TITLE
Problems authentication to Twitter

### ISSUE THREAD

**Issue by FabioSilvaBRZ** [simov/purest#24]
Hi, there. 
I am using Purest (2.0) inside the Strapi server.
For a few social media (Face, Github, Google) I have no problems.
But now I am trying to enable Twitter OAuth and I get only a:
```
"errors": [
    {
        "code": 215,
        "message": "Bad Authentication data."
    }
]
```
This happens AFTER it returns my valid access token (I have checked it agains Twitter):
```
access_token=73355...
access_secret=8EfsB...
Is there any requirement I am missing? It works only with HTTPS? Any clues?
twitter.query().get('users/show').auth(access_token).request(function (err, res, body)...
```
Thank you for your time!

**Comment by simov** [comment]
```js
var twitter = Purest({provider.., config.., key: '[OAUTH_APP_KEY]', secret: '[OAUTH_APP_SECRET]'})
twitter.get('users/show').auth(access_token, access_secret)
```

So you need both `access_token` and `access_secret` for OAuth1.0, and you need to specify the OAuth app credentials as well.

Let me know if that makes sense.

**Comment by FabioSilvaBRZ** [comment]
It seems to make sense... if I understand the documentation, Here is the authorization I am submitting:
"Authorization": "OAuth 
	oauth_nonce=\"18300e22861b414cb0fa00a580b73496\",
	oauth_signature=\"%2BshbOvkrPhFLsWVFh4Gx8vq3l%2B8%3D\""
	oauth_signature_method=\"HMAC-SHA1\",
	oauth_timestamp=\"1484856745\",
	oauth_token=\"73355715-3ibTRfKgxL9BsqebFqbw2Egr275IinXmWvr207Myr\",	
	oauth_version=\"1.0\",

It seems it lacks the oauth_consumer_key and that is the problem... how to send it, where to set it?

**Comment by simov** [comment]
```js
var purest = require('purest')({request: require('request')})

var twitter = purest({
  provider: 'twitter', config: require('@request/providers'), 
  key: 'OAUTH_CONSUMER_KEY', secret: 'OAUTH_CONSUMER_SECRET'
})

twitter
  .get('users/show')
  .auth('OAUTH_ACCESS_TOKEN', 'OAUTH_ACCESS_SECRET')
  .request((err, res, body) => {})
```

**Comment by FabioSilvaBRZ** [comment]
The request above is this one?

https://www.npmjs.com/package/request

**Comment by FabioSilvaBRZ** [comment]
I have used this:
const Purest = require('purest');
...
const twitter = new Purest({
  provider: 'twitter',
  key: 'ALk4al...', 
  secret: 'v5RJO...'
});
...
twitter.query().get('users/show').auth(access_token).request(function (err, res, body)
....

And now I have:
 "Authorization": "OAuth oauth_consumer_key=\"ALk4alKRmbtX36sfT0TKXPYUo\",oauth_nonce=\"6683708f771b4632a0a10888309e5279\",oauth_signature_method=\"HMAC-SHA1\",oauth_timestamp=\"1484866037\",oauth_token=\"73355715-RQm0cAWD5jYIxFcsA8HLVDWdWa7rPFp06GFfoJxnY\",oauth_version=\"1.0\",oauth_signature=\"VrHk%2FV%2BxDPPpdvbMyW92Gja2qJ4%3D\""

and a message error:
    "errors": [
        {
            "code": 32,
            "message": "Could not authenticate you."
        }
    ]

Even after explicitly authorizing it on Twitter... strange.

**Comment by simov** [comment]
OAuth1.0 requires both access_token and access_secret:

.auth(access_token, **access_secret**)

**Comment by FabioSilvaBRZ** [comment]
simov, first of all, thanks for the support!!!
I will take a look in your suggestion above, but I have a question.

In the same app we use Purest to Facebook, Github and Google, as follows:
facebook.query().get('me?fields=name,email').auth(access_token).request(function (err, res, body) {
github.query().get('user').auth(access_token).request(function (err, res, body) {
google.query('plus').get('people/me').auth(access_token).request(function (err, res, body) {

For Twitter only do I have to **add** the **access_secret** in the **.auth**?
twitter.query().get('users/show').auth(access_token, **access_secret**).request(function (err, res, body) {

Thanks.
By the way, we are using the Purest 2.0, ok?

**Comment by simov** [comment]
You need *4* things when using OAuth1.0 compared to just *1* when using OAuth2. Take a look at my comment from above https://github.com/simov/purest/issues/24#issuecomment-273918697 - you need to replace *all 4* uppercase strings with your app and user credentials.

**Comment by FabioSilvaBRZ** [comment]
I have been trying a lot of things here... by the way, Purest seems to be passing all parameters correctly:

```
headers":{
	"connection":"close",
	"content-length":"64",
	"content-type":"application/json; charset=utf-8",
	"date":"Wed, 25 Jan 2017 08:10:37 GMT",
	"server":"tsa_o",
	"set-cookie":["guest_id=v1%3A148533183777618650; Domain=.twitter.com; Path=/; Expires=Fri, 25-Jan-2019 08:10:37 UTC"],"strict-transport-security":"max-age=631138519","x-connection-hash":"7e39c4a99444e12a2d2a20b6492732cf","x-response-time":"103"},
	"request":{"uri":{
			"protocol":"https:",
			"slashes":true,
			"auth":null,
			"host":"api.twitter.com",
			"port":443,
			"hostname":"api.twitter.com",
			"hash":null,
			"search":null,
			"query":null,
			"pathname":"/1.1/users/show.json",
			"path":"/1.1/users/show.json",
			"href":"https://api.twitter.com/1.1/users/show.json"},
	"method":"GET","headers":{
			"accept":"application/json",
			"Authorization":"OAuth 
					oauth_consumer_key=\"XDRwB3eD4dLz1x38J7mhHnzZq\",
					oauth_nonce=\"0d8bb34e98a245e7b1fd4456a249d24f\",
					oauth_signature=\"jp1zyPffGD3CrwhZWRJ55FzTqb0%3D\",
					oauth_signature_method=\"HMAC-SHA1\",
					oauth_timestamp=\"1485331837\",
					oauth_token=\"73355715-6ewU2uaWaWXOYPGk4NU8eCp9WyciyDO6hEeXOPkuw\",
					oauth_version=\"1.0\""}}}
```

**Comment by simov** [comment]
Ok, did you succeed in making request to the Twitter API?

**Comment by FabioSilvaBRZ** [comment]
Not really...
```
    "errors": [
        {
            "code": 32,
            "message": "Could not authenticate you."
        }
    ]

```
And this is the callback...

```
debug: GET /auth/twitter/callback?
access_token=73355715-K3loow2o3X7l4blilObLrCXu7vhfGDQ5RyXBbO7Po&
access_secret=nfEdmSQeg1IPapDjpUQJeRG64ZGMEtqaME9AmY8tXfWso&
raw%5Boauth_token%5D=73355715-K3loow2o3X7l4blilObLrCXu7vhfGDQ5RyXBbO7Po&
raw%5Boauth_token_secret%5D=nfEdmSQeg1IPapDjpUQJeRG64ZGMEtqaME9AmY8tXfWso&
raw%5Buser_id%5D=73355715&
raw%5Bscreen_name%5D=fabiordasilva&
raw%5Bx_auth_expires%5D=0

```

**Comment by simov** [comment]
Paste the request code here.

**Comment by FabioSilvaBRZ** [comment]
Just a few context here:

1) Using Purest inside of Strapi... and working just smoothly with Facebook, Google and Github OAuth.

2) in the Strap's grant.js I have:
```
const twitter = new Purest({
  provider: 'twitter', 
  key: 'XDRwB3eD4dLz1x38J7mhHnzZq', 
  secret: 'qaqeCB2Drhwk19A8wfanGbZtrcHAdkZaitsoHTSc20vbttDS1j' 
});
```
and the call:
```
twitter.query().get('users/show').auth(access_token).request(function (err, res, body) {
  if (err) {
    callback(err);
  } else {
    callback(null, {
      username: body.displayName,
      email: body.emails[0].value
    });
  }
});

```
3) the error message:
```
"errors": [
	{
	    "code": 32,
	    "message": "Could not authenticate you."
	}
]

```
4) The response object:
`{"statusCode":401,"body":{"errors":[{"code":32,"message":"Could not authenticate you."}]},"headers":{"connection":"close","content-length":"64","content-type":"application/json; charset=utf-8","date":"Wed, 25 Jan 2017 10:00:57 GMT","server":"tsa_o","set-cookie":["guest_id=v1%3A148533845757010940; Domain=.twitter.com; Path=/; Expires=Fri, 25-Jan-2019 10:00:57 UTC"],"strict-transport-security":"max-age=631138519","x-connection-hash":"deaea08c5c4acf90015b4cff5e394f7e","x-response-time":"103"},
`
5) The request object:
`{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.twitter.com","port":443,"hostname":"api.twitter.com","hash":null,"search":null,"query":null,"pathname":"/1.1/users/show.json","path":"/1.1/users/show.json","href":"https://api.twitter.com/1.1/users/show.json"},"method":"GET","headers":{"accept":"application/json","Authorization":"OAuth oauth_consumer_key=\"XDRwB3eD4dLz1x38J7mhHnzZq\",oauth_nonce=\"4bf98f09ee5341b496c5c3732cce4343\",oauth_signature=\"TCuXHsYoRVVlQWWXQ701vmZo23E%3D\",oauth_signature_method=\"HMAC-SHA1\",oauth_timestamp=\"1485338457\",oauth_token=\"73355715-K3loow2o3X7l4blilObLrCXu7vhfGDQ5RyXBbO7Po\",oauth_version=\"1.0\""}}}`

6) The callback:
`GET /auth/twitter/callback?access_token=73355715-K3loow2o3X7l4blilObLrCXu7vhfGDQ5RyXBbO7Po&access_secret=nfEdmSQeg1IPapDjpUQJeRG64ZGMEtqaME9AmY8tXfWso&raw%5Boauth_token%5D=73355715-K3loow2o3X7l4blilObLrCXu7vhfGDQ5RyXBbO7Po&raw%5Boauth_token_secret%5D=nfEdmSQeg1IPapDjpUQJeRG64ZGMEtqaME9AmY8tXfWso&raw%5Buser_id%5D=73355715&raw%5Bscreen_name%5D=fabiordasilva&raw%5Bx_auth_expires%5D=0 (123ms)
`
I hope I have sent what you asked for...
Thanks!

**Comment by simov** [comment]
Change this line:

```js
twitter.query().get('users/show').auth(access_token).request(..
```

to:

```js
twitter.query().get('users/show').auth(access_token, access_secret).request(..
```

When you initially authenticate with Twitter you receive both `access_token` and `access_secret`.

The rest of the providers that you are using have implemented OAuth 2.0 which uses only `access_token`.

Twitter on the other hand implements OAuth 1.0 which uses both `access_token` and `access_secret`.

**Comment by FabioSilvaBRZ** [comment]
There is something really crazy (or really stupid hahahaha) here:

New syntax:
`twitter.query().get('users/show').auth(access_token, access_secret).request(function (err, res, body) {`

New error:
```
error: Looking for profile error: {
    "errors": [
        {
            "code": 50,
            "message": "User not found."
        }
    ]
}
```

**Comment by simov** [comment]
Add:

```js
.qs({user_id: 'your user id'})
```

or:

```js
.qs({screen_name: 'your screen name'})
```

Read carefully the Twitter's API documentation.

**Comment by FabioSilvaBRZ** [comment]
Hey, this way it returns the data!
But it took A LOT of time before finishing it... it is like a loop... strange.
I have even changed it to account/settings to see if less data is returned...

**Comment by FabioSilvaBRZ** [comment]
It was slow because de callback was looking for the e-mail that is NOT in the response... for some reason.
I am rechecking the configs to understand why...
Anyway, thanks for your help @simov 
It was really a great help!

**Comment by FabioSilvaBRZ** [comment]
Documentation says I have to pass a "include_email" => "true"

Can I use the something like that?
`.qs({include_email: 'true'})`

**Comment by FabioSilvaBRZ** [comment]
Well, if it helps anyone to setup a Twitter OAuth, here is how it is in the end:

```
const twitter = new Purest({
  provider: 'twitter'
});

```
And then:
```
twitter
  .query()
  .get('account/verify_credentials')
  .auth(oauth_query.access_token, oauth_query.access_secret)
  .qs({screen_name: oauth_query['raw[screen_name]']})
  .qs({include_email: 'true'})
  .request(function (err, res, body) {

  if (err) {
    callback(err);
  } else {
    callback(null, {
      username: body.screen_name,
      email: body.email
    });
  }

```
I hope it is useful to anyone.

**Comment by simov** [comment]
Thanks for the feedback, I'm glad it worked out for you!

**Comment by FabioSilvaBRZ** [comment]
@simov  Yes, it did! By the way, congrats for Purest!
Thanks!
