### ISSUE TITLE
Proxy and redirection URLs

### ISSUE THREAD

**Issue by FabioSilvaBRZ** [simov/purest#25]
Good morning.

I have the following scenario:  my app is behind a proxy (port 80) who redirects all incoming requests to my app (port 1337 / Strapi). It works very fine until I try to use the OAuth. 
All OAuth requests come back in the port 1337 (app original request).
How can I tell Purest to use port 80 (proxy) to the OAuth process?

I have been trying to pass it as an request option:
`options = 'http://XXXXXX/auth/facebook/callback';`
`facebook.query().get('me?fields=name,email').auth(access_token).request(options, function (err, res, body)...`

And it appears as 'callback'!!!
`2017-02-10T08:50:48.278Z - info: GET: opt: {
    "api": "__default",
    "auth": {
        "bearer": "EAAB7Tv9D...ZChAZD"
    },
    "uri": "me?fields=name,email",
    "callback": "http://XXXXXX/auth/facebook/callback",
    "method": "GET",
    "json": true
}`

But it still tries the port 1337... I force and error (shutdown the app) and I see it is still trying the callback in the port 1337...

I think it is just a config problem, because I have been using the Purest and it is quite an amazing product. Can you help me again to find the correct config to work behind a proxy??? By the way, a Nginx proxy.

Thank you!!!

**Comment by FabioSilvaBRZ** [comment]
Another example, I am trying to set the option redirect_uri but it has no effect.
`req_options = {redirect_uri: 'http://XXXXXXX/auth/facebook/callback'};`

`...
 "uri": "me?fields=name,email",
    "callback": {
        "redirect_uri": "http://XXXXXX/auth/facebook/callback"
    },
...`

It still has the 1337 port:
https://www.facebook.com/dialog/oauth?client_id=135579220267628&response_type=code&redirect_uri=http%3A%2F%2Fwww.ifuture.com.br%3A1337%2Fconnect%2Ffacebook%2Fcallback&scope=email

**Comment by FabioSilvaBRZ** [comment]
The last config generated this... but it did not work...

>     "callback": {
>        "redirect_uri": "http://www.XXXXcom.br/auth/facebook/callback",
>        "followRedirect": "true",
>        "followAllRedirects": "true",
>        "proxy": "http://www.XXXX.com.br:80",
>        "tunnel": "true"

**Comment by FabioSilvaBRZ** [comment]
One more test trying to set options... sorry for the mess but I am trying... :)

>opt: {
>    "api": "__default",
>    "auth": {
>        "bearer": "EAAB7XX...XXPFMZD"
>    },
>    "uri": "me?fields=name,email",
>    "callback": {
>        "timeout": 1500,
>        "redirect_uri": "http://www.XXXX.com.br/auth/facebook/callback",
>        "proxy": "http://www.XXXX.com.br:80",
>        "base_url": "http://www.XXXX.com.br/auth/facebook/callback",
>        "base_uri": "http://www.XXXX.com.br/auth/facebook/callback"
>    },
>    "method": "GET",
>    "json": true,
>    "redirect_uri": "http://www.XXXX.com.br/auth/facebook/callback",
>    "timeout": 1500,
>    "proxy": "http://www.XXXX.com.br:80"
>}

**Comment by simov** [comment]
You can pass request options like this:

```js
facebook
  .query()
  .get('me?fields=name,email')
  .options({proxy: '...'})
  .auth(access_token)
  .request(options, function (err, res, body)...
```

**Comment by FabioSilvaBRZ** [comment]
@simov Thank you for your return.
Now it seems to affect it somehow but the request still has the redirect_uri pointing to the port 1337.
And now I receive this error message:
{"message":"tunneling socket could not be established, cause=Parse Error"}

Still working on it...

**Comment by FabioSilvaBRZ** [comment]
The thing is: how can I 'overwrite' the `redirect_uri`???
In the request options I have now:

>  opt: {
    "api": "__default",
    "timeout": 1500,
    "redirect_uri": " **http://www.XXX.com.br/auth/facebook/callback **",
    "auth": {
        "bearer": "EAAB7Tv9DUmwBAJ..."
    },
    "uri": "me?fields=name,email",
    "method": "GET",
    "json": true
}

But the 'handshake' already starts with '1337', as follows:
Name: oauth?client_id=1355228&response_type=code&**redirect_uri=http://www.XXX.com.br:1337/connect/facebook/callback** &scope=email
Initiator: http://www.XXX.com.br/connect/facebook

Anyway, the final callback comes as:
**http://www.XXX.com.br:1337/auth/facebook/callback** ?access_token=EAAB7Tv9DU...

Why the port do NOT change?

**Comment by FabioSilvaBRZ** [comment]
In fact, I tried to 'overwrite' one of the options (`"uri": "me?fields=name,email"`) but it does not change when i get it in the `before:{ all: function...`

**Comment by FabioSilvaBRZ** [comment]
Closing the issue: the application had a configuration to address the problem.
Anyway, thanks for the support.

**Comment by FabioSilvaBRZ** [comment]
Closing the issue: the application had a configuration to address the problem.
Anyway, thanks for the support.
