### ISSUE TITLE
Problem with Flickr

### ISSUE THREAD

**Issue by aaronplanell** [simov/purest#26]
Hi!!!

I'm pretty sure that I'm doing something wrong. I'm using [simon/grant](https://github.com/simov/grant) and I've arrived to the final part of the documentation. 

Currently I've an object called _connectionData_ with this data:
```
--------------------- Connection Data ---------------------
 - user_nsid____________:  148575064@N08
 - username_____________:  Aaron Planell López
 - fullname_____________:  Aaron Planell López
 - oauth_consumer_key___:  b7718b2dc66dee760a0f66c56f507434
 - oauth_token__________:  72157677842047494-3de54641555f2d90
 - oauth_token_secret___:  0f34d5ea18ad68bf
 - access_token_________:  72157679332129251-4c25dc1c269191d0
 - access_secret________:  29160d1e6fed3e28
----------------------------------------------------------
```

I've created a function for calling the _flickr.test.login_ method of the [Flickr API](https://www.flickr.com/services/api/flickr.test.login.html)

```
var request = require('request')
var promise = require('bluebird')
var purest = require('purest')({request, promise})
var config = require('@purest/providers')

export const testLoginWithPurest = (connectionData) => {
  console.log('Inside testLoginWithPurest');

  var flickr = purest({provider: 'flickr', config,
    auth: {
      token: connectionData.oauth_token,
      secret: connectionData.oauth_token_secret
    }
  });

  flickr
    .get('flickr.test.login')
    .qs({api_key: connectionData.oauth_consumer_key})
    .auth(connectionData.access_token, connectionData.access_secret)
    .request(function (err, res, body) {
      console.log('err: ', err);
      console.log('res: ', res);
      console.log('body: ', body);
    })

  console.log('Outside testLoginWithPurest');
}
```

At the console, after validate the credentials in Flickr and after do the call to the testLoginWithPurest method, I see:
```
Inside testLoginWithPurest
Outside testLoginWithPurest
```

But, that's all. No error, no response, no body :cry: What I'm doing wrong?

PS: [Here](https://github.com/aaronplanell/flickr-backend-example/tree/vDevelop) you will find my project   if you wanna check the calculation of the _connectionData_ variable.

Best regards!!!

**Comment by simov** [comment]
You should change:

```js
var flickr = purest({provider: 'flickr', config,
    auth: {
      token: connectionData.oauth_token,
      secret: connectionData.oauth_token_secret
    }
  });
```

to:

```js
var flickr = purest({provider: 'flickr', config,
      key: connectionData.oauth_token,
      secret: connectionData.oauth_token_secret
  });
```

Let me know if it works.

**Comment by aaronplanell** [comment]
Hi!

Thanks a lot for your quick answer. 
Sorry... Doesn't work. Same problem :disappointed: 

Any other ideas?

**Comment by aaronplanell** [comment]
And I tried avoid using _purest_ in another [branch](https://github.com/aaronplanell/flickr-backend-example/commits/vDevelopWithoutPurest) using only grant and I've got _oauth_problem=token_used_.

**Comment by aaronplanell** [comment]
Hi again!

I refactored the github branchs:
- [vDevelop](https://github.com/aaronplanell/flickr-backend-example/tree/vDevelop): No login test. Only get the tokens for making requests.
- [vDevelopWithPurest](https://github.com/aaronplanell/flickr-backend-example/tree/vDevelopWithPurest): Login test with Purest. No answer.
- [vDevelopWithoutPurest](https://github.com/aaronplanell/flickr-backend-example/tree/vDevelopWithoutPurest): Login test without Purest. Answer _oauth_problem=token_used_

All it's very weird. At least at the [vDevelopWithPurest](https://github.com/aaronplanell/flickr-backend-example/tree/vDevelopWithPurest) I must have some kind of error but I have no answer :cry: 

Thanks a lot for your help!

**Comment by simov** [comment]
This works:

```js
var promise = require('bluebird')
var request = require('@request/client')
var purest = require('purest')({request, promise})
var flickr = purest({
  provider: 'flickr',
  config: require('@purest/providers'),
  key: 'your application key here',
  secret: 'your application secret here'
})

flickr
  .get()
  .qs({
    method: 'flickr.test.login',
    api_key: 'your application key here'
  })
  .auth('your access token here', 'your access secret here')
  .request()
  .then(([res, body]) => {
    console.log(body)
  })
  .catch((err) => console.log(err))
```

I know because I just tested it :)

As you can see the actual endpoint `flickr.test.login` is passed in the querystring. That's specific to the Flickr API. Also take a look at this [example](https://github.com/request/request/tree/master/examples#flickr-image-upload) on how to upload images.

**Comment by aaronplanell** [comment]
Thanks a lot!!! It was perfect. 

I modify my function with your code:
```
import promise from 'bluebird';
import request from '@request/client';
var purest = require('purest')({request, promise})

//Constants
import { FLICKR_CONSUMER_KEY, FLICKR_CONSUMER_SECRET } from './constants';

export const testLoginWithPurest = (connectionData) => {
  var flickr = purest({
    provider: 'flickr',
    config: require('@purest/providers'),
    key: FLICKR_CONSUMER_KEY,
    secret: FLICKR_CONSUMER_SECRET
  })

  flickr
    .get()
    .qs({
      method: 'flickr.test.login',
      api_key: FLICKR_CONSUMER_KEY
    })
    .auth(connectionData.access_token, connectionData.access_secret)
    .request()
    .then(([res, body]) => {
      console.log(body);
      return body;
    })
    .catch((err) => console.log(err))
}
```

And now returns me _stat: 'ok'_
```
--------------------- Connection Data ---------------------
 - user_nsid____________:  148575064@N08
 - username_____________:  Aaron Planell López
 - fullname_____________:  Aaron Planell López
 - oauth_consumer_key___:  b7718b2dc66dee760a0f66c56f507434
 - oauth_token__________:  72157681232074416-ccbe0bb62a2bc6fb
 - oauth_token_secret___:  620a9d0f14774abd
 - access_token_________:  72157679332129251-4c25dc1c269191d0
 - access_secret________:  29160d1e6fed3e28
-----------------------------------------------------------
{ user: 
   { id: '148575064@N08',
     username: { _content: 'Aaron Planell López' } },
  stat: 'ok' }
```

Perfect! Now I will proxy some functions to my Express server and I will continue with the front part. Thanks a lot Simov for solving the issue and thanks a lot, too, for your work :+1: 

Best regards from Barcelona!
