### ISSUE TITLE
An example for twitter oauth1 call

### ISSUE THREAD

**Issue by bitinn** [simov/purest#3]
I have the access token at this point, but does `.auth(access_token)` work with oauth1?

my setup:

```
var opts = {
	key: ...
	, secret: ...
 	, provider: 'twitter'
	, access_token: ...
};
var client = new Purest(opts);
client.query()
	.get('account/verify_credentials')
	.auth(opts.access_token)
	.request(function(err, res, body) {
		...
	});
```

Twitter return `code: 32, message: 'Could not authenticate you.'` with status code 401.

**Comment by bitinn** [comment]
found it, in here: https://github.com/simov/purest/blob/master/config/providers.json#L1776

**Comment by bitinn** [comment]
wait, i still can't get pass it with `.auth(opts.access_token, opts.secret)`...

**Comment by bitinn** [comment]
ah, of course, oauth1 use `access_token` and `access_secret` https://github.com/simov/grant#oauth1

**Comment by simov** [comment]
Yeah you can check out the https://github.com/simov/grant/blob/master/config/oauth.json file if you are in doubt which version of OAuth the provider is using.
