### ISSUE TITLE
Response does't parsed JSON even set content-type to application/json

### ISSUE THREAD

**Issue by smoothdvd** [simov/purest#32]
```
const weixin = purest({
    provider: 'weixin-miniprogram',
    defaults: {
      headers: {
        'Content-Type': 'application/json',
      },
    },
    config: {
      'weixin-miniprogram': {
        default: {
          origin: 'https://api.weixin.qq.com',
          path: 'sns/{path}',
          qs: { appid: '{auth}', secret: '{auth}', type: 'json' },
        },
      },
    },
  });
```

**Comment by simov** [comment]
The `content-type` header have to be set by the server, not by you. You can install [request-logs](https://github.com/simov/request-logs) and see what headers the server returns. If the headers are not correct then Purest won't try to parse the body.

**Comment by smoothdvd** [comment]
@simov No, it's not very accurate. As mentioned, "Content-Type.....In requests, (such as POST or PUT), the client tells the server what type of data is actually sent." [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type)

**Comment by simov** [comment]
The title of your issues says 'Response' not request, so what is the issue exactly?
