### ISSUE TITLE
try to use `simple-get`?

### ISSUE THREAD

**Issue by tunnckoCore** [simov/purest#8]
It would be good if you can migrate to smaller lib. `simple-get` can do almost everything, except that it not returns readable stream as `request` do but there some tricks.

**Comment by simov** [comment]
There is an ongoing effort to split what `request` offers into smaller modules, and I don't think migrating to `simple-get` is the way to go. Request offers **much** more than that.

As far as `purest` is concerned, there will be an option to switch between HTTP clients in future. The API itself and configuration will remain the same.

**Comment by tunnckoCore** [comment]
Alright. Great to hear.

Cheers, from Bulgaria :beer: lol
